[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.targets.wheel]
packages = ["bids/ext/reports"]

[tool.hatch.build.hooks.vcs]
version-file = "bids/ext/reports/_version.py"

[project]
name = "pybids_reports"
description = "pybids-reports: report generator for BIDS datasets"
authors = [{ name = "PyBIDS Developers", email = "bids-discussion@googlegroups.com"}]
maintainers = [{ name = "PyBIDS Developers", email = "bids-discussion@googlegroups.com" }]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
dependencies = [
  "chevron",
  "pybids>=0.15",
  "nibabel",
  "num2words",
  "rich"
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Console",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Topic :: Scientific/Engineering",
]
dynamic = ["version"]

[project.scripts]
pybids_reports = "reports.cli:cli"

[project.urls]
Homepage = "http://github.com/bids-standard/pybids-reports"
Documentation = "https://cohort-creator.readthedocs.io/en/latest/"
"Bug trakcer" = "http://github.com/bids-standard/pybids-reports/issues"

[project.optional-dependencies]
doc = [
	"numpydoc",
	"sphinx",
	"furo",
  "myst-parser",
  "sphinx-argparse",
  "sphinx-copybutton"
]
docs=["pybids_reports[doc]"]
test = [
    "codecov",
    "flake8-black",
    "flake8-docstrings",
    "flake8-isort",
    "pytest>=3.3",
    "pytest-cov",
]
tests=["pybids_reports[test]"]
ci_tests = [
  "pybids_reports[test]",
  "pytest-xdist"
]
dev = [
  "pybids_reports[doc]",
  "pybids_reports[test]"
]

[tool.black]
line-length = 99
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.github
    | \.hg
    | \.pytest_cache
    | _build
    | build
    | dist
  )/
  | bids/ext/reports/_version.py
  | bids/ext/reports/due.py
)
'''

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.codespell]
skip = "./.git,versioneer.py,_version.py,bids/ext/reports/tests/data/*"
ignore-words-list = "te"

[tool.mypy]
exclude = ['bids/ext/reports/tests/']

[[tool.mypy.overrides]]
module = [
    'ext.reports.tests.*',
    'ext.reports._version.*',
    'ext.reports.due.*',
    'ext.versioneer.*',
]
ignore_errors = true
