---
name: Run Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - '*'

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Determine if tests should be run based on commit message.
  check_skip:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.result_step.outputs.ci-skip }}
    steps:
    - id: result_step
      uses: mstachniuk/ci-skip@master
      with:
        commit-filter: '[skip ci];[ci skip];[skip github];[no ci]'
        commit-filter-separator: ;

  run_tests:
    needs: check_skip
    if: ${{ needs.check_skip.outputs.skip == 'false' }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} with Python ${{ matrix.python-version }}
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      shell: bash {0}
      run: python -c "import sys; print(sys.version)"
    - name: Install pybids-reports
      shell: bash {0}
      run: pip install .[tests]
    - name: Run tests
      shell: bash {0}
      run: python -m pytest --pyargs bids/ext/reports --cov=bids/ext/reports
    - name: Upload coverage to CodeCov
      uses: codecov/codecov-action@v3
      if: success()

  test_cli:
    needs: check_skip
    if: ${{ needs.check_skip.outputs.skip == 'false' }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.11']
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} with Python ${{ matrix.python-version }}
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      shell: bash {0}
      run: python -c "import sys; print(sys.version)"
    - name: Install bids examples
      run: git clone https://github.com/bids-standard/bids-examples.git
    - name: Install pybids-reports
      shell: bash {0}
      run: pip install .
    - name: Info CLI
      shell: bash {0}
      run: |
        pybids_reports --version
        pybids_reports --help
    - name: Run test for CLI
      shell: bash {0}
      run: |
        bash tools/run_on_examples.sh
